
version: "2"

services:
  graphite-statsd:
   image: graphiteapp/graphite-statsd
   ports:
    - "80:80"
    - "8125:8125/udp"

  grafana:
   image: grafana/grafana
   ports:
    - "3000:3000"
   volumes:
    - type: bind
      source: ./datasources
      target: /etc/grafana/provisioning/datasources/

